spring:
  application:
    name: jchatmind
  datasource:
    url: jdbc:postgresql://localhost:5432/jchatmind
    username: postgres
    password: 991225
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 770138585@qq.com
    password: your-password # 邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ai:
    deepseek:
      api-key: sk-5e2efc310f7b40328c1ad51e93c5f112
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    zhipuai:
      api-key: 3b74e09395bf496e8b06a93f159de57b.V7S6HQ1jKhggZOfV
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.6
mybatis:
  type-aliases-package: com.kama.jchatmind.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.kama.jchatmind.typehandler

document:
  storage:
    base-path: ./data/documents
